name: Build artifact
on: [push, workflow_call]
jobs:
  # Build the website and create artifacts
  build_and_create_artifact:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build the website
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      # Zip the dist folder into dist.zip file
      - name: Zip dist
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dist.zip dist
      
      # Add the dist.zip file as an artifact for the build
      - name: Upload deployment artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-package
          path: dist.zip

      # Create a tar artifact file for github-pages
      - name: Tar dist
        shell: sh
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "$INPUT_PATH" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            .
        env:
          INPUT_PATH: dist

      # Add the tar file as an artifact for the build
      - name: Upload gh-pages artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 0
          if-no-files-found: error
