name: Build artifacts
on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  # Build the website and create artifacts
  build_and_create_artifact:
    name: Build and create artifacts
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build the website
      - name: Build npm commands
        run: |
          npm install
          npm run build --if-present

      # Download a version of the latest GeoView Core build
      - uses: suisei-cn/actions-download-file@v1.3.0
        id: downloadfile  # Remember to give an ID if you need the output filename
        name: Download the file
        with:
          url: "https://canadian-geospatial-platform.github.io/geoview/public/cgpv-main.js"
          target: dist/

      # Add the dist.zip file as an artifact for the build
      - name: Upload deployment artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-package
          path: dist

      # Push to the gh-pages branch
      - name: Push to gh-pages branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages # The branch name where you want to push the assets
          FOLDER: dist # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
