name: Release
on:
  push:
    tags:
      - '*'

jobs:
  # Build the artifacts
  build_artifacts:
    name: Build the artifacts
    uses: ./.github/workflows/build.yml

  # Add the artifact to the release
  add_artifact_to_the_release:
    name: Attach artifacts to the release
    needs: build_artifacts
    runs-on: ubuntu-latest
    steps:
      
      # Download the artifact from the tag
      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-package
          path: dist
      
      # Zip the dist folder into dist.zip file
      - name: Zip dist
        run: zip -r dist.zip .
        working-directory: dist

      #- name: Echo output
      #  run: echo ${{steps.download.outputs.download-path}}
      
      #- name: Display structure of downloaded files
      #  run: ls -R
      #  working-directory: ${{steps.download.outputs.download-path}}

      # Add the artifact to the release
      - name: Add the zipped artifact to the release
        uses: softprops/action-gh-release@v1
        with:
          files: dist.zip
