name: Release
on:
  push:
    tags:
      - '*'

jobs:
  # Build the artifacts
  build_artifacts:
    uses: ./.github/workflows/build.yml

  # Add the artifact to the release
  add_artifact_to_the_release:
    name: release_artifacts
    needs: build_artifacts
    runs-on: ubuntu-latest
    steps:
      
      # Download the artifact from the tag
      - name: download_artifact
        uses: actions/download-artifact@v3
        id: download
        with:
          name: dist-package
          path: ~/dist
      
      #- name: Echo output
      #  run: echo ${{steps.download.outputs.download-path}}
      
      #- name: Display structure of downloaded files
      #  run: ls -R
      #  working-directory: ${{steps.download.outputs.download-path}}

      # Add the artifact to the release
      - name: add_artifact_to_release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{steps.download.outputs.download-path}}/*
