name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build_artifact:
    uses: ./.github/workflows/build.yml
  build_release:
    name: build_release
    needs: build_artifact
    runs-on: ubuntu-latest
    steps:
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          #release_name: ${{ steps.version.outputs.version }}
          release_name: coucou
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: attach release asset artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/dist-package.zip
          asset_name: dist.zip
          asset_content_type: application/gzip
