name: Release
on:
  push:
    tags:
      - '*'

jobs:
  build_artifacts:
    uses: ./.github/workflows/build.yml
  
  add_artifact_to_the_release:
    name: build_release
    needs: build_artifacts
    runs-on: ubuntu-latest
    steps:
      - name: download_artifact
        uses: actions/download-artifact@v3
        id: download
        with:
          name: dist-package
          path: ~/dist
      #- name: Echo output
      #  run: echo ${{steps.download.outputs.download-path}}
      #- name: Display structure of downloaded files
      #  run: ls -R
      #  working-directory: ${{steps.download.outputs.download-path}}
      - name: add_artifact_to_release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{steps.download.outputs.download-path}}/*

  # Deploy job
  push_artifact_to_github_pages:
    # Add a dependency to the build artifact
    needs: build_artifacts

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
